/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.actions.demo.java;

public class App {
    /**
     * getGreeting().
     */
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * main().
     */
    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
